version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install -r test-requirements.txt
      - run: pytest
workflows:
  version: 2
  build:
    jobs:
      - test
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
